config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :beers

  resources :breweries

  resources :ratings, only: [:index, :new, :create, :destroy]

  get 'signup', to: 'users#new'
  
  root 'breweries#index'

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  
  delete 'signout', to: 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratebeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navibar">
    <%= link_to 'breweries', breweries_path %>
    <%= link_to 'beers', beers_path %>
    <%= link_to 'ratings', ratings_path %>
    <%= link_to 'users', users_path %> |
    <% if not current_user.nil? %>
      <%= link_to current_user.username, current_user %>
      <%= link_to 'rate a beer', new_rating_path %>
      <%= link_to 'signout', signout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <% if current_user.nil? %>
      <%= link_to 'signin', signin_path %>
      <%= link_to 'signup', new_user_path %>
    <% end %>

  </div>
 
  <% if session[:last_rating].nil? %>
   <p>no ratings given</p>
   <% else %>
   <p>previous rating: <%= session[:last_rating] %></p>
  <% end %>

 
  <% if not current_user.nil? %>
    <p><%= current_user.username %> signed in</p>
  <% end %>

  <%= yield %>

</body>
</html>